### ISSUE TITLE
Add modevents to allow player to start as character in Stories (LAL compatibility)

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SkLLmods#389]
[Planned.. and subject to change]
 
I am sexbot waking up in a Dwemer forge.
:: SendModEvent("_SLS_PCStartSexbot")
:: If Stories and player female, Start as ELLE-type bot deep inside Sex bots forge (spark spells, rebuild yourself, cast large stackable debuff of magicka/stamina/health at night + dispel after sex)
:: Fetish - Needs sex once a day
 
I am the Pet of a necromancer.
:: SendModEvent("_SLS_PCStartPet")
:: If Stories and player female, Start as Pet (with Belethor as brother + transformation as Fire atronach when free of devices)
:: Fetish - get hit once a day while wearing a device
 
I am a working girl in the Red Wave brothel.
:: SendModEvent("_SLS_PCStartRedWave")
:: If Stories, Start as a whore in the Red Wave (with large debt + quest to lure replacement)
:: Fetish - talk to someone naked while wearing jewelry once a day
 
I am a cow in a milk farm.
:: SendModEvent("_SLS_PCStartMilkFarm")
:: If Stories Devious and player female, Start as a cow in the milking farm (already harnessed)
:: Fetish - produce milk or sex with animal once a day
 
I am a Brood Maiden of the Chaurus.
:: SendModEvent("_SLS_PCStartBroodMaiden")
:: If Estrus Chaurus and player female, Start as a follower of the Brood Maiden (already infected)
:: Fetish - sex with chaurus or falmer once a day
 
I am an Alicia, promised to Lord Sanguine.
:: SendModEvent("_SLS_PCStartAlicia")
:: If SD, start as an Alicia in Dreamworld (with custom dialogues)
:: Fetish - get hit once a day while wearing a device
 
I am a Spriggan Host, devoted to Kyne.
:: SendModEvent("_SLS_PCStartSpriggan")
:: If SD, start as spriggan host in pond near Falkreath (with power to transform into full spriggan)
:: Fetish - Swim once a day

**Comment by ContentConsumer** [comment]
Just double-checking - should there also be a "player must be female" check on the working girl, alicia, and spriggan host starts?

**Comment by SkyrimLL** [comment]
If it's not too much trouble, yes.. that would be nice for Alicia and the Brood Maiden mostly.

The Red Wave has male 'workers' already and the Spriggan roots are indiscriminate about the gender of their host :)

**Comment by ContentConsumer** [comment]
I'll check, but I think I already put in a "must be female" check on the brood maiden start. But I did forget to do so for Alicia, no idea why. :)
