### ISSUE TITLE
Add dialogue topics for removal of parasites

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SkLLmods#463]
- Danica Pure-Spring
- Apothecaries
- Priests
- Vigilants of Stendaar

**Comment by HerrNachtmahr** [comment]
Should not your spouse also be able to help you ? at the end who wants to have intercourse with a woman/man with eggs/rotting eggs in her.

**Comment by SkyrimLL** [comment]
It will be based on job/faction. If your spouse is a priest or apothecary, she will be able to help.
My plan is to make only certain parasites removable with small remedies (fire, potions). Larger and nastier ones will be removable only with the help of Danica Pure-Spring (and for the cost of materials... like finding dwemer oil or troll fat or fire salts...).

**Comment by HerrNachtmahr** [comment]
nice is more dynamic and fun to actually have to go to more experienced healers  for nastier things.
