### ISSUE TITLE
Wrong language

### ISSUE THREAD

**Issue by TheMadModder** [SkyrimLL/SkLLmods#579]
I don't see an option for english, but it is not in english. How do I change the language?

**Comment by TheMadModder** [comment]
Can anyone help me? Am i missing a download? I have the mods it requires. I downloaded the top 3 files and installed the the second one first, then the first one and then the third. Looks like everything works, mod wise, but I can't read the language for the mod's dialogue.

**Comment by SkyrimLL** [comment]
Answered in LL forums
