### ISSUE TITLE
Standing Stone Fetish applies before accepting a perk

### ISSUE THREAD

**Issue by ThisIsPatrick** [SkyrimLL/SkLLmods#586]
Checking a standing stone will apply a fetish regardless of if the standing stone perk is accepted or not.
The fetish text also will clip off the side of the screen if the text is too long.

I've noticed Shout Like a Virgin also applies it's standing stone love even if a standing stone perk is not accepted, so I'm assuming checking if the perk is accepted is a limitation?

**Comment by SkyrimLL** [comment]
You can clear the fetish by clicking on the stone again, regardless if you accept or not.

The acceptance of a perk from the stone is separate from the act of activating the stone (which is what Stories looks for).
