### ISSUE TITLE
MCM menu issues

### ISSUE THREAD

**Issue by ThisIsPatrick** [SkyrimLL/SkLLmods#617]
Having made many new characters I've noticed that some of the SexLab Hormones MCM menu sliders don't start on their default values. Upon further examination of the SLH_QST_ConfigMenu.psc script I noticed that some mcm toggles are set as unchecked in OnDefaultST() yet show up checked on a fresh game.

In an attempt to fix these issues I went into the script and changed the values in OnDefaultST(), compiled it, yet upon a fresh start of Skyrim the values did not change.
`event OnDefaultST() GV_useColors.SetValueInt( 0 ) SetToggleOptionValueST( false ) endEvent`

I can find no other places in the SLH scripts for where these values are set, only where the values are retrieved. I've also tried changing the other values in SLH_QST_ConfigMenu with no changes showing in the MCM.

Thinking this was an issue exclusively with SLH I checked out the SexLab Dialogues sld_mcm.psc, changing the same related values, compiled and ran into the same issue - the changes do not show up on a fresh game start.

What am I doing wrong here? I'd really like to help out, I've been fiddling with this for weeks off and on as a starting point in learning papyrus scripting. Looking through the SkyUI GitHub Wiki for the correct usage of MCM State Options everything looks correct.

**Comment by SkyrimLL** [comment]
Dissecting someone else's mod is a great way to learn Papyrus. That's how I got started actually.

Part of the problem, I think, is that I use too many global variables instead of relying only on storageUtil variables. My next rewrite of Hormones will be about gettin grid of global variables altogether.

For now, which MCM sliders are having issues in particular?

I just fixed an issue with the Max Schlong size slider, which was not set correctly. A fix for that is in the last beta version I think. Anything else I should look into?

**Comment by ThisIsPatrick** [comment]
I'd like the change weight scale, skin color, and hair color toggles to default to off. The others aren't a serious issue.

It's also common for the reported shape values in the Add-ons MCM to be something other than 1.0 at the start of a new game (possibly due to node changes being on by default.)

The following MCM sliders are set to a value that is not their default when starting a new game:
```
High Sex Activity trigger 3 (expected 2)
Low Sex Activity buffer 3 (expected 7)
Weight swell mod -1.0 (expected 1.0)
Breast swell max 3.0 (expected 2.0)
Belly swell min 0.9 (expected 0.8)
Belly swell max 2.4 (expected 1.2)
Butt swell min 0.9 (expected 0.8)
Beg arousal trigger 98.0 (expected 60.0)
NPC Comments Frequency 30.0% (expected 80.0%)
```
The following MCM toggles default to a state opposite the private variables set in
SLH_QST_ConfigMenu.psc:
```
Change Weight scale on (expected off)
Change skin color on (expected off)
Change hair color on (expected off)
Drop items when aroused on (expected off)
Shape change override on (expected off)
Show Status message off (expected on)
Allow Exhibitionist on (expected off)
Allow Self Spells on (expected off)
Debug messages on (expected off)
```

**Comment by SkyrimLL** [comment]
The default values in the MCM script itself are overridden right away by default values from the global variables. They should be ignored.
