### ISSUE TITLE
YPS lipstick and eye shadow are being applied everyday

### ISSUE THREAD

**Issue by ThisIsPatrick** [SkyrimLL/SkLLmods#729]
Starting after 15 days as a Bimbo, YPS lipstick and eye shadow is made permanent.
However, the event continues to happen every day thereafter.
Every 24 hours the lipstick, eyeshadow, no smudging, locked makeup, and permanent makeup events happen again, even though it's been applied already.

This seems to lock player controls while the event is happening.
Shouldn't these only be applied once, or at least not as often as every 24 hours?

**Comment by SkyrimLL** [comment]
Thanks. I will review that along with similar issues I noticed with making the curse permanent.

I agree I shouldn't reapply anything that can be locked for good within the YPS framework.
