### ISSUE TITLE
GlobalVariable Properties missing from slh_qst_bimboalias

### ISSUE THREAD

**Issue by ThisIsPatrick** [SkyrimLL/SkLLmods#730]
`ERROR: Cannot call SetValue() on a None object, aborting function call
stack:
	[alias _SLH_REF_BimboPlayerShape on quest _SLH_Bimbo (77015161)].slh_qst_bimboalias.bimboDailyProgressiveTransformation() - "SLH_QST_BimboAlias.psc" Line 892
	[alias _SLH_REF_BimboPlayerShape on quest _SLH_Bimbo (77015161)].slh_qst_bimboalias.OnUpdate() - "SLH_QST_BimboAlias.psc" Line 219`

The **GlobalVariable Property GV_isBimboFinal** and **GV_isBimboLocked** for _slh_qst_bimboalias_ are not linked on the Creation Kit side of the script.

**Comment by SkyrimLL** [comment]
Fixed and linked to #732
