### ISSUE TITLE
Replace Game.GetPlayer() calls with a PlayerRef property

### ISSUE THREAD

**Issue by ThisIsPatrick** [SkyrimLL/SkLLmods#748]
Game.GetPlayer() calls are slow and inefficient, replace all the calls by adding an Actor PlayerRef property in the Creation Kit pointing to PlayerRef [PLYR:00000014]

**Comment by SkyrimLL** [comment]
I have been trying to reduce the number of calls to Game.GetPlayer().
My problem with using a fixed ref is the detection of racial transformations like with vampires or werewolves. 
I do know the fixed ref in SexLab doesn't change when the player is transformed. I haven't tried with PlayerRef [PLYR:00000014]

**Comment by SkyrimLL** [comment]
What I try to do, instead of replacing it by a static reference, is to minimize the number of calls to GetPlayer(). 

Closing this issue for now to clean up my to-do list.
