### ISSUE TITLE
Big white exclamation mark in a red square when having spider eggs or chaurus worms

### ISSUE THREAD

**Issue by Daveedmee** [SkyrimLL/SkLLmods#749]
My character is shown in a red square with a white exclamation mark when she is infected with spider eggs or chaurus worms. Plz help
![156130234782495624585](https://user-images.githubusercontent.com/52132306/59978114-328c2d00-95d9-11e9-8901-da116c58a075.jpg)

**Comment by SkyrimLL** [comment]
Please ask this kind of questions in the main forum thread and not in Github: https://www.loverslab.com/topic/22195-sexlab-hormones-may-2019/

Typically, this kind of red squares are a sign that your game does not recognize the paths to the meshes. 

Check the configuration of your mod management tool. Chances are , it is not copying all the files where they are supposed to go.
