### ISSUE TITLE
Reduce the size of Bimbo popups to prevent truncated notifications

### ISSUE THREAD

**Issue by rdhughes** [SkyrimLL/SkLLmods#918]
The notifications for the bimbo stages is being cut off so that you don't see all of it. I'm running a 2k monitor in native resolution, so I don't know if my monitor resolution isn't high enough, or what the issue is exactly. Nor do I have a suggestion for how to address it other than reducing the amount of text or else having the courier deliver notes from a "friend" as the stages progress. Or more work, but adding a quest to find a journal from a previous bimbo outlining their transformation could work too.

**Comment by ThisIsPatrick** [comment]
Why not simply split them into two separate notifications instead.
There's no need to impose a limit on the amount of possible narration just because it doesn't fit in a single line.

**Comment by SkyrimLL** [comment]
I didn't reduce them drastically. I just trimmed them a little bit and removed some parts that were immersion breaking (like comments about Belethor). You can look at the bimbo alias script in the code. The comments are still very similar.
